name = "nisoje-api"
main = "worker.js"
compatibility_date = "2026-04-11"

[vars]
FIREBASE_API_KEY = "AIzaSyBWRMoHbPNkOw0zvflcPb_dv9G1Bgg1uLc"
GAMES_CATALOG_OBJECT = "catalog/latest.json"
GAME_DOWNLOAD_TTL_SECONDS = "300"
ADMIN_EMAIL = "nisojestudio@gmail.com"
INSTALLER_URL = "https://github.com/nisojestudio/launcher/releases/download/instalador/PanelLive-3.0-Windows-x64-Setup.exe"

[[d1_databases]]
binding = "DB"
database_name = "nisoje-db"
database_id = "dc6e836d-ab30-46af-b029-402a6f4f819e"

[[r2_buckets]]
binding = "GAMES_CATALOG_BUCKET"
bucket_name = "games-catalog"
