name = "nisoje-api-dev"
main = "worker.js"
compatibility_date = "2026-04-11"

[vars]
GAMES_CATALOG_OBJECT = "catalog/latest.json"
GAME_DOWNLOAD_TTL_SECONDS = "300"
ADMIN_EMAIL = "nisojestudio@gmail.com"
INSTALLER_URL = "https://github.com/nisojestudio/launcher/releases/download/v0.1.4/panel-live-0.1.4-win-x64.exe"
CORS_ALLOW_ORIGIN = "https://nisoje.com"
RESEND_FROM_EMAIL = "soporte@nisoje.com"
MOBILE_APK_URL = "https://github.com/nisojestudio/panel-live-mobil-releases/releases/download/v1.0.9-debug/panel-live-mobil-1.0.9-debug.apk"

[[d1_databases]]
binding = "DB"
database_name = "nisoje-db"
database_id = "dc6e836d-ab30-46af-b029-402a6f4f819e"

[[r2_buckets]]
binding = "GAMES_CATALOG_BUCKET"
bucket_name = "games-catalog"
preview_bucket_name = "games-catalog"
